export const toResults = () => "/wyniki";
export const toGames = () => "/gry";
export const toUsers = () => "/uzytkownicy";
export const toStats = () => "/statystyki-gier";
export const toLogin = () => "/logowanie";
export const toNewResult = () => "/nowy-wynik";
export const toNewGame = () => "/gry/nowa";
export const toUserStats = () => "/moje-statystyki";
export const toHomePage = () => "/";
export const toGame = ({ id } = { id: ":id" }) => `/gry/${id}`;